#include "stdafx.h"


void Ragdoll_Basic::constructBasicDoll()
{
	numParticles=30;
	numLinks=68;

	particle = new RagdollParticle[numParticles];

	//Head, neck, and chest
	particle[RAGBASIC_HEADLEFT].Set(-0.055110f,2.0f,0.000000f,0.1f,RAGBASIC_HEADLEFT);
	particle[RAGBASIC_HEADRIGHT].Set(0.055110f,2.0f,0.000000f,0.1f,RAGBASIC_HEADRIGHT);
	particle[RAGBASIC_NECK].Set(0.000000f,1.745363f,0.000000f,0.1f,RAGBASIC_NECK);
	particle[RAGBASIC_CHEST].Set(0.000000f,1.436749f,0.000000f,0.1f,RAGBASIC_CHEST);
	
	//Waist
	particle[RAGBASIC_WAISTLEFT].Set(-0.188279f,1.19813f,0.000000f,0.1f,RAGBASIC_WAISTLEFT);
	particle[RAGBASIC_WAISTRIGHT].Set(0.188279f,1.19813f,0.000000f,0.1f,RAGBASIC_WAISTRIGHT);

	//Left arm
	particle[RAGBASIC_HANDLEFT].Set(-1.111011f,1.600000f,0.000000f,0.1f,RAGBASIC_HANDLEFT);
	particle[RAGBASIC_BICEPLEFT].Set(-0.591588f,1.65782f,0.070813f,0.1f,RAGBASIC_BICEPLEFT);
	particle[RAGBASIC_TRICEPLEFT].Set(-0.591588f,1.65782f,-0.070813f,0.1f,RAGBASIC_TRICEPLEFT);
	particle[RAGBASIC_UPELBOWLEFT].Set(-0.678951f,1.721530f,0.000000f,0.1f,RAGBASIC_UPELBOWLEFT);
	particle[RAGBASIC_LOWELBOWLEFT].Set(-0.678951f,1.600000f,0.000000f,0.1f,RAGBASIC_LOWELBOWLEFT);
	particle[RAGBASIC_SHOULDERLEFT].Set(-0.246891f,1.666339f,0.000000f,0.1f,RAGBASIC_SHOULDERLEFT);

	//Right arm
	particle[RAGBASIC_HANDRIGHT].Set(1.111011f,1.600000f,0.000000f,0.1f,RAGBASIC_HANDRIGHT);
	particle[RAGBASIC_BICEPRIGHT].Set(0.591588f,1.65782f,0.070813f,0.1f,RAGBASIC_BICEPRIGHT);
	particle[RAGBASIC_TRICEPRIGHT].Set(0.591588f,1.65782f,-0.070813f,0.1f,RAGBASIC_TRICEPRIGHT);
	particle[RAGBASIC_UPELBOWRIGHT].Set(0.678951f,1.721530f,0.000000f,0.1f,RAGBASIC_UPELBOWRIGHT);
	particle[RAGBASIC_LOWELBOWRIGHT].Set(0.678951f,1.600000f,0.000000f,0.1f,RAGBASIC_LOWELBOWRIGHT);
	particle[RAGBASIC_SHOULDERRIGHT].Set(0.246891f,1.666339f,0.000000f,0.1f,RAGBASIC_SHOULDERRIGHT);
	
	//Left leg
	particle[RAGBASIC_LEGTOPLEFT].Set(-0.13131f,0.951243f,0.000000f,0.1f,RAGBASIC_LEGTOPLEFT);
	particle[RAGBASIC_QUADLEFT].Set(-0.211058f,0.550156f,0.075043f,0.1f,RAGBASIC_QUADLEFT);
	particle[RAGBASIC_HAMLEFT].Set(-0.211058f,0.550156f,-0.075043f,0.1f,RAGBASIC_HAMLEFT);
	particle[RAGBASIC_OUTKNEELEFT].Set(-0.271140f,0.488410f,0.000000f,0.1f,RAGBASIC_OUTKNEELEFT);
	particle[RAGBASIC_INKNEELEFT].Set(-0.180760f,0.488410f,0.000000f,0.1f,RAGBASIC_INKNEELEFT);
	particle[RAGBASIC_FOOTLEFT].Set(-0.271140f,0.0f,0.000000f,0.05f,RAGBASIC_FOOTLEFT);

	//Right leg
	particle[RAGBASIC_LEGTOPRIGHT].Set(0.13131f,0.951243f,0.000000f,0.1f,RAGBASIC_LEGTOPRIGHT);
	particle[RAGBASIC_QUADRIGHT].Set(0.211058f,0.550156f,0.075043f,0.1f,RAGBASIC_QUADRIGHT);
	particle[RAGBASIC_HAMRIGHT].Set(0.211058f,0.550156f,-0.075043f,0.1f,RAGBASIC_HAMRIGHT);
	particle[RAGBASIC_OUTKNEERIGHT].Set(0.271140f,0.488410f,0.000000f,0.1f,RAGBASIC_OUTKNEERIGHT);
	particle[RAGBASIC_INKNEERIGHT].Set(0.180760f,0.488410f,0.000000f,0.1f,RAGBASIC_INKNEERIGHT);
	particle[RAGBASIC_FOOTRIGHT].Set(0.271140f,0.0f,0.000000f,0.05f,RAGBASIC_FOOTRIGHT);

	//Make normal links
	link = new RagdollLink[numLinks];

	//Head
	link[0].Set(&particle[RAGBASIC_HEADLEFT],&particle[RAGBASIC_HEADRIGHT]);
	link[1].Set(&particle[RAGBASIC_HEADLEFT],&particle[RAGBASIC_NECK]);
	link[2].Set(&particle[RAGBASIC_HEADRIGHT],&particle[RAGBASIC_NECK]);

	//Upper torso
	link[3].Set(&particle[RAGBASIC_SHOULDERLEFT],&particle[RAGBASIC_NECK]);
	link[4].Set(&particle[RAGBASIC_SHOULDERRIGHT],&particle[RAGBASIC_NECK]);
	link[5].Set(&particle[RAGBASIC_SHOULDERLEFT],&particle[RAGBASIC_CHEST]);
	link[6].Set(&particle[RAGBASIC_SHOULDERRIGHT],&particle[RAGBASIC_CHEST]);
	link[7].Set(&particle[RAGBASIC_SHOULDERLEFT],&particle[RAGBASIC_WAISTLEFT]);
	link[8].Set(&particle[RAGBASIC_SHOULDERRIGHT],&particle[RAGBASIC_WAISTRIGHT]);
	link[9].Set(&particle[RAGBASIC_NECK],&particle[RAGBASIC_CHEST]);
	link[10].Set(&particle[RAGBASIC_WAISTLEFT],&particle[RAGBASIC_CHEST]);
	link[11].Set(&particle[RAGBASIC_WAISTRIGHT],&particle[RAGBASIC_CHEST]);
	link[12].Set(&particle[RAGBASIC_WAISTLEFT],&particle[RAGBASIC_WAISTRIGHT]);

	//Lower torso
	link[13].Set(&particle[RAGBASIC_WAISTLEFT],&particle[RAGBASIC_LEGTOPLEFT]);
	link[14].Set(&particle[RAGBASIC_WAISTLEFT],&particle[RAGBASIC_LEGTOPRIGHT]);
	link[15].Set(&particle[RAGBASIC_WAISTRIGHT],&particle[RAGBASIC_LEGTOPLEFT]);
	link[16].Set(&particle[RAGBASIC_WAISTRIGHT],&particle[RAGBASIC_LEGTOPRIGHT]);
	link[17].Set(&particle[RAGBASIC_LEGTOPLEFT],&particle[RAGBASIC_LEGTOPRIGHT]);

	//Left arm
	link[18].Set(&particle[RAGBASIC_SHOULDERLEFT],&particle[RAGBASIC_UPELBOWLEFT]);
	link[19].Set(&particle[RAGBASIC_SHOULDERLEFT],&particle[RAGBASIC_LOWELBOWLEFT]);
	link[20].Set(&particle[RAGBASIC_SHOULDERLEFT],&particle[RAGBASIC_BICEPLEFT]);
	link[21].Set(&particle[RAGBASIC_SHOULDERLEFT],&particle[RAGBASIC_TRICEPLEFT]);
	link[22].Set(&particle[RAGBASIC_BICEPLEFT],&particle[RAGBASIC_UPELBOWLEFT]);
	link[23].Set(&particle[RAGBASIC_BICEPLEFT],&particle[RAGBASIC_LOWELBOWLEFT]);
	link[24].Set(&particle[RAGBASIC_TRICEPLEFT],&particle[RAGBASIC_UPELBOWLEFT]);
	link[25].Set(&particle[RAGBASIC_TRICEPLEFT],&particle[RAGBASIC_LOWELBOWLEFT]);
	link[26].Set(&particle[RAGBASIC_UPELBOWLEFT],&particle[RAGBASIC_LOWELBOWLEFT]);
	link[27].Set(&particle[RAGBASIC_UPELBOWLEFT],&particle[RAGBASIC_HANDLEFT]);
	link[28].Set(&particle[RAGBASIC_LOWELBOWLEFT],&particle[RAGBASIC_HANDLEFT]);

	//Right arm
	link[29].Set(&particle[RAGBASIC_SHOULDERRIGHT],&particle[RAGBASIC_UPELBOWRIGHT]);
	link[30].Set(&particle[RAGBASIC_SHOULDERRIGHT],&particle[RAGBASIC_LOWELBOWRIGHT]);
	link[31].Set(&particle[RAGBASIC_SHOULDERRIGHT],&particle[RAGBASIC_BICEPRIGHT]);
	link[32].Set(&particle[RAGBASIC_SHOULDERRIGHT],&particle[RAGBASIC_TRICEPRIGHT]);
	link[33].Set(&particle[RAGBASIC_BICEPRIGHT],&particle[RAGBASIC_UPELBOWRIGHT]);
	link[34].Set(&particle[RAGBASIC_BICEPRIGHT],&particle[RAGBASIC_LOWELBOWRIGHT]);
	link[35].Set(&particle[RAGBASIC_TRICEPRIGHT],&particle[RAGBASIC_UPELBOWRIGHT]);
	link[36].Set(&particle[RAGBASIC_TRICEPRIGHT],&particle[RAGBASIC_LOWELBOWRIGHT]);
	link[37].Set(&particle[RAGBASIC_UPELBOWRIGHT],&particle[RAGBASIC_LOWELBOWRIGHT]);
	link[38].Set(&particle[RAGBASIC_UPELBOWRIGHT],&particle[RAGBASIC_HANDRIGHT]);
	link[39].Set(&particle[RAGBASIC_LOWELBOWRIGHT],&particle[RAGBASIC_HANDRIGHT]);
	
	//Left leg
	link[40].Set(&particle[RAGBASIC_LEGTOPLEFT],&particle[RAGBASIC_INKNEELEFT]);
	link[41].Set(&particle[RAGBASIC_LEGTOPLEFT],&particle[RAGBASIC_OUTKNEELEFT]);
	link[42].Set(&particle[RAGBASIC_LEGTOPLEFT],&particle[RAGBASIC_QUADLEFT]);
	link[43].Set(&particle[RAGBASIC_LEGTOPLEFT],&particle[RAGBASIC_HAMLEFT]);
	link[44].Set(&particle[RAGBASIC_QUADLEFT],&particle[RAGBASIC_INKNEELEFT]);
	link[45].Set(&particle[RAGBASIC_QUADLEFT],&particle[RAGBASIC_OUTKNEELEFT]);
	link[46].Set(&particle[RAGBASIC_HAMLEFT],&particle[RAGBASIC_INKNEELEFT]);
	link[47].Set(&particle[RAGBASIC_HAMLEFT],&particle[RAGBASIC_OUTKNEELEFT]);
	link[48].Set(&particle[RAGBASIC_INKNEELEFT],&particle[RAGBASIC_OUTKNEELEFT]);
	link[49].Set(&particle[RAGBASIC_INKNEELEFT],&particle[RAGBASIC_FOOTLEFT]);
	link[50].Set(&particle[RAGBASIC_OUTKNEELEFT],&particle[RAGBASIC_FOOTLEFT]);

	//Right leg
	link[51].Set(&particle[RAGBASIC_LEGTOPRIGHT],&particle[RAGBASIC_INKNEERIGHT]);
	link[52].Set(&particle[RAGBASIC_LEGTOPRIGHT],&particle[RAGBASIC_OUTKNEERIGHT]);
	link[53].Set(&particle[RAGBASIC_LEGTOPRIGHT],&particle[RAGBASIC_QUADRIGHT]);
	link[54].Set(&particle[RAGBASIC_LEGTOPRIGHT],&particle[RAGBASIC_HAMRIGHT]);
	link[55].Set(&particle[RAGBASIC_QUADRIGHT],&particle[RAGBASIC_INKNEERIGHT]);
	link[56].Set(&particle[RAGBASIC_QUADRIGHT],&particle[RAGBASIC_OUTKNEERIGHT]);
	link[57].Set(&particle[RAGBASIC_HAMRIGHT],&particle[RAGBASIC_INKNEERIGHT]);
	link[58].Set(&particle[RAGBASIC_HAMRIGHT],&particle[RAGBASIC_OUTKNEERIGHT]);
	link[59].Set(&particle[RAGBASIC_INKNEERIGHT],&particle[RAGBASIC_OUTKNEERIGHT]);
	link[60].Set(&particle[RAGBASIC_INKNEERIGHT],&particle[RAGBASIC_FOOTRIGHT]);
	link[61].Set(&particle[RAGBASIC_OUTKNEERIGHT],&particle[RAGBASIC_FOOTRIGHT]);


	//Don't let head get too close to chest
	link[62].Set(&particle[RAGBASIC_HEADLEFT],&particle[RAGBASIC_CHEST],RAGLINK_MINIMUM,0.48f*0.48f);
	link[63].Set(&particle[RAGBASIC_HEADRIGHT],&particle[RAGBASIC_CHEST],RAGLINK_MINIMUM,0.48f*0.48f);

	//Don't let head get too close or far away from shoulders 
	link[64].Set(&particle[RAGBASIC_HEADLEFT],&particle[RAGBASIC_SHOULDERLEFT],RAGLINK_MINMAX,0.13f*0.13f,0.51f*0.51f);
	link[65].Set(&particle[RAGBASIC_HEADRIGHT],&particle[RAGBASIC_SHOULDERRIGHT],RAGLINK_MINMAX,0.13f*0.13f,0.51f*0.51f);

	//Rotational head restraint
	link[66].Set(&particle[RAGBASIC_SHOULDERRIGHT],&particle[RAGBASIC_HEADLEFT],&particle[RAGBASIC_HEADRIGHT],0.05f);
	link[67].Set(&particle[RAGBASIC_SHOULDERLEFT],&particle[RAGBASIC_HEADRIGHT],&particle[RAGBASIC_HEADLEFT],0.05f);

	
	
}
