//
// DYNAMIC ARRAY MANAGEMENT
//

// 0-9 DWORD * 10 = upto ten values to help locate an array-element
// 10  DWORD SIZE OF ARRAY
// 11  DWORD SIZE OF ONE ARRAY ELEMENT
// 12  DWORD TYPE VALUE OF ARRAY ELEMENT
// 13  DWORD INTERNAL ARRAY INDEX FOR STACKS AND STUFF
#define HEADERSIZEINBYTES 56
